### PR TITLE
Search bar

### PR DESCRIPTION
**Pull request by VernitaJ**
2 commits. One from Paula and one from Farooq. fixes#18

### CODE REVIEW

**Comment by VernitaJ** [comment]
On the first render, all users should appear, until onChange is fired. At the moment, on first render, the screen just says 'Loading...'
image

**Comment by paulatorre** [comment]
> On the first render, all users should appear, until onChange is fired. At the moment, on first render, the screen just says 'Loading...'
> 
_Yeah I know, I put some comments on HomeView where I'm managing the state. Not sure how to solve it because I thought this was enough 
const [searchResults, setSearchResults] = useState([users]);_ 

> image

**Comment by Deve1980** [comment]
Hi @paulatorre

**Comment by paulatorre** [comment]
Hej @Deve1980  :)
Do you mean in the UseEffect? 
(I was playing with use ref and adding some extra lines so now I'm lost with the order I had before)
Thanks!

> Hi @paulatorre
> Try to add setSearchResults(users) to the line 15

**Comment by Deve1980** [comment]
If you want to view users from  first time you loading the page

**Comment by paulatorre** [comment]
yes, I want that! I didn't understand where to add what you suggested (setSearchResults(users)) because now my line 15 has a different code

**Comment by Deve1980** [comment]
in the useEffect that used to  FOCUS ON SEARCH INPUT

**Comment by paulatorre** [comment]
Finally fixed by adding a "users" as a second dependency of the use effect that handles the filter

**Comment by VernitaJ** [comment]
> Finally fixed by adding a "users" as a second dependency of the use effect that handles the filter

Did you mean to close this request?

**Pull request closed without merging**
