### PR TITLE
Search bar

### PR DESCRIPTION
**Pull request by paulatorre**
Create Search bar and new stateless components to isolate the state. 
Modified CSS according to the new components

### CODE REVIEW

**Comment by paulatorre** [comment]
Yes. It has many conflicts 😅 
Mainly because I modified the home view. But I tried to be careful and include the things that were already committed and merged to the master.

**Comment by paulatorre** [comment]
Hi everyone, please review this and comment. I was thinking maybe we could add a default profile photo when it is not included in the DB, and it's necessary to re-include the loading indicator in the new components but associated with the data fetching. Does anyone want to do this?

**Comment by VernitaJ** [comment]
The search function isn't working on my side, but I see there have been 2 approvals, so I am wondering if it is just on my side?

image

**Comment by paulatorre** [comment]
Thanks, Vernita! ;)
I'm gonna fix it. 
I have to improve the filter.
 It worked at the beginning because the first users on the DB had similar id's and name+surname.

**Comment by farooq029** [comment]
@paulatorre it's not looking good when search.
You should change the style on the search 





Screenshot 2020-03-10 at 07 22 47

**Comment by farooq029** [comment]
Otherwise, search function working fine and design is good other then this mentioned

**Comment by VernitaJ** [comment]
I agree with @farooq029. Maintain the width as in home-view. Otherwise, it's fine.

**Comment by paulatorre** [comment]
Thank you guys, will fix that now. didn't realize how awful it looks :P

**Pull request merged**
